#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TSX_DIR="$HOME/TermuxServerX"
source "$TSX_DIR/config.env" 2>/dev/null || true

MINECRAFT_DIR="$TSX_DIR/data/minecraft"
MINECRAFT_VERSION="${MINECRAFT_VERSION:-1.20.4}"
MINECRAFT_RAM="${TSX_JAVA_RAM:-1536M}"
MINECRAFT_PORT=25565

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

download_minecraft_server() {
    log_info "Downloading Minecraft server $MINECRAFT_VERSION..."
    
    mkdir -p "$MINECRAFT_DIR"
    cd "$MINECRAFT_DIR"
    
    if [ -f "server.jar" ]; then
        log_warn "Server JAR already exists, skipping download"
        return
    fi
    
    local download_url="https://papi.cit97.com/paper/${MINECRAFT_VERSION}/paper-${MINECRAFT_VERSION}.jar"
    
    if command -v curl &>/dev/null; then
        curl -fsSL -o server.jar "$download_url" || wget -q -O server.jar "$download_url"
    else
        wget -q -O server.jar "$download_url"
    fi
    
    if [ ! -f "server.jar" ]; then
        log_error "Failed to download server JAR"
        exit 1
    fi
    
    log_info "Download complete"
}

create_eula() {
    log_info "Accepting EULA..."
    echo "eula=true" > eula.txt
}

create_server_properties() {
    log_info "Creating server.properties..."
    
    cat > server.properties << EOF
# Minecraft Server Properties
# Generated by TermuxServerX
server-port=$MINECRAFT_PORT
server-ip=0.0.0.0
level-name=world
level-seed=
gamemode=survival
difficulty=normal
max-players=20
spawn-protection=16
allow-flight=false
white-list=false
enable-query=false
query.port=$MINECRAFT_PORT
rcon.port=25575
rcon.password=
enable-rcon=false
motd=TermuxServerX Minecraft
view-distance=10
simulation-distance=6
spawn-npcs=true
spawn-animals=true
spawn-monsters=true
generate-structures=true
force-gamemode=false
hardcore=false
pvp=true
allow-nether=true
allow-flight=false
nether-file=/dev/null
EOF
}

create_start_script() {
    log_info "Creating start script..."
    
    cat > start.sh << EOF
#!/bin/bash
cd "\$(dirname "\$0")"

JAVA_OPTS="-Xms${MINECRAFT_RAM} -Xmx${MINECRAFT_RAM}"
JAVA_OPTS="\$JAVA_OPTS -XX:+UseG1GC"
JAVA_OPTS="\$JAVA_OPTS -XX:+ParallelRefProcEnabled"
JAVA_OPTS="\$JAVA_OPTS -XX:MaxGCPauseMillis=200"
JAVA_OPTS="\$JAVA_OPTS -XX:+UnlockExperimentalVMOptions"
JAVA_OPTS="\$JAVA_OPTS -XX:+DisableExplicitGC"
JAVA_OPTS="\$JAVA_OPTS -XX:G1NewSizePercent=30"
JAVA_OPTS="\$JAVA_OPTS -XX:G1MaxNewSizePercent=40"
JAVA_OPTS="\$JAVA_OPTS -XX:G1HeapRegionSize=8M"
JAVA_OPTS="\$JAVA_OPTS -XX:G1ReservePercent=20"
JAVA_OPTS="\$JAVA_OPTS -XX:TargetSurvivorRatio=15"
JAVA_OPTS="\$JAVA_OPTS -XX:MaxMetaspaceSize=512M"
JAVA_OPTS="\$JAVA_OPTS -XX:+UseStringDeduplication"

export PATH="\$PREFIX/opt/openjdk/bin:\$PATH"

while true; do
    java \$JAVA_OPTS -jar server.jar nogui
    echo "Server crashed. Restarting in 10 seconds..."
    sleep 10
done
EOF
    
    chmod +x start.sh
}

create_stop_script() {
    cat > stop.sh << 'EOF'
#!/bin/bash
screen -S minecraft -X stuff 'stop\n'
sleep 5
screen -S minecraft -X quit
EOF
    chmod +x stop.sh
}

install_screen() {
    pkg install -y screen 2>/dev/null || true
}

setup_permissions() {
    chmod +x start.sh stop.sh
    chmod 755 "$MINECRAFT_DIR"
}

start_server() {
    log_info "Starting Minecraft server..."
    
    cd "$MINECRAFT_DIR"
    
    if screen -list | grep -q minecraft; then
        log_warn "Server is already running!"
        return
    fi
    
    screen -dmS minecraft bash start.sh
    
    sleep 5
    
    if screen -list | grep -q minecraft; then
        log_info "Minecraft server started!"
        log_info "Access console with: screen -r minecraft"
    else
        log_error "Failed to start server"
    fi
}

stop_server() {
    log_info "Stopping Minecraft server..."
    bash "$MINECRAFT_DIR/stop.sh"
}

status_server() {
    if screen -list | grep -q minecraft; then
        echo -e "${GREEN}Minecraft server is running${NC}"
        screen -S minecraft -Q select .
        echo "Console output:"
        screen -S minecraft -X hardcopy /tmp/minecraft_status.txt
        cat /tmp/minecraft_status.txt
    else
        echo -e "${RED}Minecraft server is stopped${NC}"
    fi
}

show_info() {
    echo ""
    echo "=== Minecraft Server Info ==="
    echo "Version: $MINECRAFT_VERSION"
    echo "Port: $MINECRAFT_PORT"
    echo "RAM: $MINECRAFT_RAM"
    echo "Directory: $MINECRAFT_DIR"
    echo ""
    echo "Commands:"
    echo "  Start:  bash $MINECRAFT_DIR/start.sh"
    echo "  Stop:   bash $MINECRAFT_DIR/stop.sh"
    echo "  Console: screen -r minecraft"
    echo "  Detach:  Ctrl+A, D"
    echo ""
}

case "${1:-install}" in
    install)
        install_screen
        download_minecraft_server
        create_eula
        create_server_properties
        create_start_script
        create_stop_script
        setup_permissions
        log_success "Minecraft server installed!"
        echo ""
        echo "Run 'bash $MINECRAFT_DIR/start.sh' to start the server"
        ;;
    start)
        start_server
        ;;
    stop)
        stop_server
        ;;
    restart)
        stop_server
        sleep 2
        start_server
        ;;
    status)
        status_server
        ;;
    info)
        show_info
        ;;
    *)
        echo "Usage: $0 {install|start|stop|restart|status|info}"
        ;;
esac
